In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import yfinance as yf

In [14]:
url = 'https://www.fundamentus.com.br/resultado.php'
agent = {'User-Agent':'Mozzila/5.0'}
resposta = requests.get(url, headers=agent)
soup = BeautifulSoup(resposta.text, 'lxml')
tabela = soup.find_all('table')[0]
df = pd.read_html(str(tabela), decimal=',', thousands='.')[0]
df

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,POPR4,10.17,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"8,66%","5,65%",1.08,"15,25%","19,93%",0.0,5.458030e+08,0.82,"30,93%"
1,PMET3,0.00,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","4,10%",0.0,-2.908630e+08,0.00,"37,74%"
2,CSTB4,147.69,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
3,MNSA3,0.42,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"-208,15%","-362,66%",3.63,"-13,50%","145,70%",0.0,-9.105000e+06,-6.52,"-41,11%"
4,CFLU4,1000.00,0.00,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"8,88%","10,72%",1.10,"17,68%","32,15%",0.0,6.035100e+07,0.06,"8,14%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,UBBR11,14.75,1201.81,3.91,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
980,UBBR3,18.00,1466.61,4.77,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
981,GLOB4,30.49,4873.60,8.59,1.512,"0,00%",1.389,-63.21,46.91,-4.59,...,28.77,"3,22%","0,03%",0.96,"3,90%","0,18%",0.0,5.675000e+09,1.76,"5,35%"
982,LWSA3,9.70,13567.30,1.94,8.244,"0,00%",1.363,3.39,181.72,5.54,...,36.99,"4,54%","0,06%",3.82,"1,33%","0,01%",131543000.0,2.950560e+09,0.04,"53,23%"
983,BBTG12,3.15,66496.50,0.00,0.000,"0,00%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,00%",0.0,0.000000e+00,0.00,"0,00%"

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Papel              984 non-null    object
 1   Cotação            984 non-null    float64
 2   P/L                984 non-null    float64
 3   P/VP               984 non-null    float64
 4   PSR                984 non-null    float64
 5   Div.Yield          984 non-null    object
 6   P/Ativo            984 non-null    float64
 7   P/Cap.Giro         984 non-null    float64
 8   P/EBIT             984 non-null    float64
 9   P/Ativ Circ.Liq    984 non-null    float64
 10  EV/EBIT            984 non-null    float64
 11  EV/EBITDA          984 non-null    float64
 12  Mrg Ebit           984 non-null    object
 13  Mrg. Líq.          984 non-null    object
 14  Liq. Corr.         984 non-null    float64
 15  ROIC               984 non-null    object
 16  ROE                984 non-null    object
 17  Liq.2meses         984 non-null    float64
 18  Patrim. Líq        984 non-null    float64
 19  Dív.Brut/ Patrim.  984 non-null    float64
 20  Cresc. Rec.5a      984 non-null    object
dtypes: float64(14), object(7)
memory usage: 161.6+ KB

In [19]:
# filtro de liquidez maior que 1mm
liquidezMaior = df[df['Liq.2meses'] >= 1000000]
liquidezMaior

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
10,GNDI3,71.20,-3812.39,6.21,3.640,"0,39%",2.528,84.70,92.58,-6.60,...,53.96,"3,93%","-0,09%",1.17,"3,09%","-0,16%",328179000.0,7.116080e+09,0.53,"25,23%"
11,APER3,34.13,-3249.18,1.77,4.066,"0,00%",1.061,7.47,-8.86,-10.31,...,-9.60,"-45,89%","-0,31%",1.92,"-15,46%","-0,05%",1794190.0,2.936510e+08,0.00,"6,64%"
13,RCSL3,4.64,-543.77,-8.05,6.471,"0,00%",5.430,79.96,384.50,-4.74,...,203.35,"1,68%","-1,18%",1.15,"1,50%","1,48%",21317600.0,-4.369800e+07,-0.00,"667,41%"
14,CASH3,2.91,-488.14,3.28,11.224,"0,20%",2.830,3.96,-257.31,4.46,...,-294.94,"-4,36%","-1,15%",21.09,"-3,63%","-0,67%",170130000.0,7.138490e+08,0.00,"0,00%"
15,DASA3,29.14,-440.75,2.15,1.601,"1,03%",0.868,19.54,101.30,-3.04,...,18.13,"1,58%","-0,26%",1.17,"1,04%","-0,49%",11987100.0,7.418660e+09,0.72,"30,37%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,BIDI11,25.98,417.64,2.62,0.000,"0,17%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,63%",406593000.0,8.536610e+09,0.00,"46,66%"
973,BIDI4,8.68,418.60,2.62,0.000,"0,17%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,63%",103585000.0,8.536610e+09,0.00,"46,66%"
975,VIIA3,4.72,754.46,1.33,0.234,"0,00%",0.215,-9.79,7.26,-0.71,...,8.04,"3,22%","0,03%",0.96,"3,90%","0,18%",193382000.0,5.675000e+09,1.76,"5,35%"
978,SEQL3,15.26,1167.15,3.53,1.505,"0,00%",1.104,20.12,120.60,-2.95,...,18.53,"1,25%","0,13%",1.21,"1,09%","0,30%",33385900.0,6.027330e+08,1.13,"0,00%"
982,LWSA3,9.70,13567.30,1.94,8.244,"0,00%",1.363,3.39,181.72,5.54,...,36.99,"4,54%","0,06%",3.82,"1,33%","0,01%",131543000.0,2.950560e+09,0.04,"53,23%"

In [22]:
# filtro de ações sem dividas
patrimonioMaior = liquidezMaior[liquidezMaior['Patrim. Líq'] >= 0]
patrimonioMaior

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
10,GNDI3,71.20,-3812.39,6.21,3.640,"0,39%",2.528,84.70,92.58,-6.60,...,53.96,"3,93%","-0,09%",1.17,"3,09%","-0,16%",328179000.0,7.116080e+09,0.53,"25,23%"
11,APER3,34.13,-3249.18,1.77,4.066,"0,00%",1.061,7.47,-8.86,-10.31,...,-9.60,"-45,89%","-0,31%",1.92,"-15,46%","-0,05%",1794190.0,2.936510e+08,0.00,"6,64%"
14,CASH3,2.91,-488.14,3.28,11.224,"0,20%",2.830,3.96,-257.31,4.46,...,-294.94,"-4,36%","-1,15%",21.09,"-3,63%","-0,67%",170130000.0,7.138490e+08,0.00,"0,00%"
15,DASA3,29.14,-440.75,2.15,1.601,"1,03%",0.868,19.54,101.30,-3.04,...,18.13,"1,58%","-0,26%",1.17,"1,04%","-0,49%",11987100.0,7.418660e+09,0.72,"30,37%"
36,ELMD3,14.67,-54.05,2.72,5.867,"0,00%",1.308,5.25,-67.82,-17.02,...,52.25,"-8,65%","-10,85%",2.29,"-3,34%","-5,03%",1782270.0,7.507270e+08,0.79,"0,00%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,BIDI11,25.98,417.64,2.62,0.000,"0,17%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,63%",406593000.0,8.536610e+09,0.00,"46,66%"
973,BIDI4,8.68,418.60,2.62,0.000,"0,17%",0.000,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,63%",103585000.0,8.536610e+09,0.00,"46,66%"
975,VIIA3,4.72,754.46,1.33,0.234,"0,00%",0.215,-9.79,7.26,-0.71,...,8.04,"3,22%","0,03%",0.96,"3,90%","0,18%",193382000.0,5.675000e+09,1.76,"5,35%"
978,SEQL3,15.26,1167.15,3.53,1.505,"0,00%",1.104,20.12,120.60,-2.95,...,18.53,"1,25%","0,13%",1.21,"1,09%","0,30%",33385900.0,6.027330e+08,1.13,"0,00%"
982,LWSA3,9.70,13567.30,1.94,8.244,"0,00%",1.363,3.39,181.72,5.54,...,36.99,"4,54%","0,06%",3.82,"1,33%","0,01%",131543000.0,2.950560e+09,0.04,"53,23%"

In [23]:
dadosFiltrados = patrimonioMaior[['Papel', 'ROIC', 'EV/EBIT']]

In [27]:
dadosFiltrados.head()

    Papel     ROIC  EV/EBIT
10  GNDI3    3,09%    96.66
11  APER3  -15,46%    -7.11
14  CASH3   -3,63%  -194.73
15  DASA3    1,04%   121.35
36  ELMD3   -3,34%   -68.32

In [53]:
dadosFiltrados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 258 entries, 10 to 982
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Papel    258 non-null    object
 1   ROIC     258 non-null    object
 2   EV/EBIT  258 non-null    float64
dtypes: float64(1), object(2)
memory usage: 8.1+ KB

In [59]:
ordemEV = dadosFiltrados.sort_values(by='EV/EBIT')
ordemEV = ordemEV.reset_index(drop=True)
ordemEV['ordemEV'] = ordemEV.index
ordemEV

     Papel    ROIC  EV/EBIT  ordemEV
0    CXSE3  -0,61%  -422.75        0
1    BRAP4  -0,23%  -289.81        1
2    BRAP3  -0,23%  -254.03        2
3    CASH3  -3,63%  -194.73        3
4    MOAR3  -2,34%  -137.35        4
..     ...     ...      ...      ...
253  AESB3   0,89%   125.02      253
254  LWSA3   1,33%   127.89      254
255  SEQL3   1,09%   147.17      255
256  POMO4   0,49%   183.11      256
257  OPCT3   0,18%   370.81      257

[258 rows x 4 columns]

In [60]:
#tratamento valores
ordemEV['ROIC'] = ordemEV['ROIC'].str.replace(',', '.')
ordemEV['ROIC'] = ordemEV['ROIC'].str.rstrip('%').astype('float') / 100

In [61]:
ordemEV.dtypes

Papel       object
ROIC       float64
EV/EBIT    float64
ordemEV      int64
dtype: object

In [62]:
ordemROIC = ordemEV.sort_values(by='ROIC', ascending=False)
ordemROIC = ordemROIC.reset_index(drop=True)
ordemROIC['ordemROIC'] = ordemROIC.index
ordemROIC

     Papel    ROIC  EV/EBIT  ordemEV  ordemROIC
0    CMIN3  0.7714     2.77       79          0
1    WIZS3  0.5873     2.61       76          1
2    PSSA3  0.5277     0.27       65          2
3    TASA4  0.4906     3.91       86          3
4    VALE3  0.4656     2.36       72          4
..     ...     ...      ...      ...        ...
253  APER3 -0.1546    -7.11       20        253
254  AZEV4 -0.1716    -6.92       21        254
255  SHOW3 -0.2052    -3.46       24        255
256  WEST3 -0.3400    -2.38       25        256
257  ENJU3 -1.8824    -1.76       26        257

[258 rows x 5 columns]

In [66]:
dadosFinal = ordemROIC
dadosFinal['Score'] = dadosFinal['ordemEV'] + dadosFinal['ordemROIC']
dadosFinal = dadosFinal.sort_values(by='Score')

In [68]:
dadosFinal.head()

   Papel    ROIC  EV/EBIT  ordemEV  ordemROIC  Score
2  PSSA3  0.5277     0.27       65          2     67
4  VALE3  0.4656     2.36       72          4     76
1  WIZS3  0.5873     2.61       76          1     77
0  CMIN3  0.7714     2.77       79          0     79
8  PLPL3  0.3905     2.53       74          8     82

In [69]:
def setorAtivo(tick):
    setor = yf.Ticker(tick)
    return setor.info['sector']

In [71]:
tickers = dadosFinal['Papel'] + '.SA'
tickers

2      PSSA3.SA
4      VALE3.SA
1      WIZS3.SA
0      CMIN3.SA
8      PLPL3.SA
         ...
189    DASA3.SA
190    AESB3.SA
188    SEQL3.SA
191    POMO4.SA
193    OPCT3.SA
Name: Papel, Length: 258, dtype: object

In [72]:
dicionarioSetores = {}
for t in tickers:
    try:
        dicionarioSetores[t] = setorAtivo(t)
        print('COLETA DE DADOS')
    except:
        print(f'ATIVO SEM COLETA : {t}')
        dicionarioSetores[t] = 'NAN'

dicionarioSetorAtivo = pd.DataFrame.from_dict(dicionarioSetores, orient='index').reset_index()
dicionarioSetorAtivo.columns = ['Papel', 'Setor']

dicionarioSetorAtivo

COLETA DE DADOS
COLETA DE DADOS
COLETA DE DADOS
COLETA DE DADOS
COLETA DE DADOS
COLETA DE DADOS
COLETA DE DADOS
COLETA DE DADOS
COLETA DE DADOS